# These are supported funding model platforms

github: omharde42
custom: "upi://pay?pa=omharde300@oksbi&pn=Om%20Harde&cu=INR" 
<iframe src="https://github.com/sponsors/omharde42/button" title="Sponsor omharde42" height="32" width="114" style="border: 0; border-radius: 6px;"></iframe>
